#!/bin/bash

# RevenueCat Installation Script
# This script guides you through installing and configuring RevenueCat

echo "================================"
echo "RevenueCat Integration Setup"
echo "================================"
echo ""

# Step 1: Install Package
echo "📦 Step 1: Installing react-native-purchases..."
echo "Run: npx expo install react-native-purchases"
echo ""
echo "⚠️  IMPORTANT: RevenueCat requires custom native code."
echo "    It will NOT work in Expo Go."
echo "    You must build a development client or production build."
echo ""
read -p "Press Enter to continue..."
echo ""

# Step 2: Configuration
echo "⚙️  Step 2: Configure RevenueCat"
echo ""
echo "You need to:"
echo "  1. Create products in App Store Connect (iOS)"
echo "     - Product ID: monthly"
echo "     - Product ID: yearly"
echo ""
echo "  2. Create products in Google Play Console (Android)"
echo "     - Product ID: monthly"
echo "     - Product ID: yearly"
echo ""
echo "  3. Configure RevenueCat Dashboard"
echo "     - Create entitlement: 'Readly Premium'"
echo "     - Create offering: 'default'"
echo "     - Add both products to the offering"
echo "     - Get your Public SDK Key"
echo ""
read -p "Press Enter to continue..."
echo ""

# Step 3: Update API Key
echo "🔑 Step 3: Update API Key"
echo ""
echo "Open: contexts/revenuecat-context.tsx"
echo "Update line: const REVENUECAT_API_KEY = 'YOUR_KEY_HERE';"
echo ""
echo "Current test key: test_EBCTTKAYreuszKiTMMyAjaLkcnF"
echo "Replace with your production key from RevenueCat dashboard"
echo ""
read -p "Press Enter to continue..."
echo ""

# Step 4: Build App
echo "🔨 Step 4: Build App"
echo ""
echo "RevenueCat doesn't work in Expo Go. Build your app:"
echo ""
echo "For iOS:"
echo "  npx expo run:ios"
echo ""
echo "For Android:"
echo "  npx expo run:android"
echo ""
echo "Or create a development build:"
echo "  npx expo prebuild"
echo "  npm run ios"
echo "  npm run android"
echo ""
read -p "Press Enter to continue..."
echo ""

# Step 5: Integrate Premium Checks
echo "✨ Step 5: Integrate Premium Checks"
echo ""
echo "Add premium checks to your share card screens:"
echo ""
echo "1. Import the hook:"
echo "   import { usePremium } from '@/contexts/revenuecat-context';"
echo ""
echo "2. Use in component:"
echo "   const { isPremium } = usePremium();"
echo ""
echo "3. Check before allowing premium themes:"
echo "   if (theme.isPremium && !isPremium) {"
echo "     // Show upgrade alert"
echo "     router.push('/paywall');"
echo "   }"
echo ""
echo "See REVENUECAT_SHARE_INTEGRATION.md for complete examples"
echo ""
read -p "Press Enter to continue..."
echo ""

# Step 6: Test
echo "🧪 Step 6: Test Subscriptions"
echo ""
echo "iOS Testing:"
echo "  1. Create sandbox tester in App Store Connect"
echo "  2. Sign out of Apple ID on device"
echo "  3. Run app and test purchase"
echo "  4. Sign in with sandbox account when prompted"
echo ""
echo "Android Testing:"
echo "  1. Add test accounts in Google Play Console"
echo "  2. Join testing track"
echo "  3. Install from testing track"
echo "  4. Test purchases (free for test accounts)"
echo ""
read -p "Press Enter to continue..."
echo ""

# Step 7: Backend Sync (Optional)
echo "🔄 Step 7: Backend Sync (Optional)"
echo ""
echo "If you want to sync premium status to Supabase:"
echo ""
echo "1. Run the SQL migration:"
echo "   Execute: SUPABASE_PREMIUM_MIGRATION.sql"
echo ""
echo "2. Add sync hook to your app:"
echo "   import useSyncPremiumWithBackend from '@/hooks/useSyncPremiumWithBackend';"
echo "   useSyncPremiumWithBackend();"
echo ""
read -p "Press Enter to continue..."
echo ""

# Summary
echo "================================"
echo "✅ Installation Guide Complete!"
echo "================================"
echo ""
echo "Next steps:"
echo "  1. Install package: npx expo install react-native-purchases"
echo "  2. Configure products in app stores"
echo "  3. Set up RevenueCat dashboard"
echo "  4. Update API key in code"
echo "  5. Build development client"
echo "  6. Add premium checks to share cards"
echo "  7. Test with sandbox accounts"
echo ""
echo "Documentation:"
echo "  - Setup Guide: REVENUECAT_SETUP.md"
echo "  - Quick Reference: REVENUECAT_QUICKSTART.md"
echo "  - Share Integration: REVENUECAT_SHARE_INTEGRATION.md"
echo "  - Summary: REVENUECAT_SUMMARY.md"
echo ""
echo "Need help? Check the documentation or visit:"
echo "  https://docs.revenuecat.com/docs/reactnative"
echo ""
echo "Good luck! 🚀"
